logging:
  level:
    com.devtest.productapi: INFO
    feign.Logger: OFF

feign:
  client:
    config:
      product-service:
        connect-timeout: 5000 # 10000
        read-timeout: 2000 # 60000
        logger-level: FULL # NONE, BASIC, HEADERS, FULL
  circuitbreaker:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
      useGzipDecoder: true

client:
  product-service:
    url: http://localhost:3001

server:
  port: 5000
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
